Deobfuscate logs using aternos/sherlock
aternosorg/mclogs pull request #22
Opened 2022-04-01 14:07 UTC by JulianVennen

Cache obfuscation maps in redis or mongodb

2022-04-05 10:24 UTC, matthi4s requested changes

2022-04-05 10:24 UTC, matthi4s commented on core/config/cache.php
> +    "cacheId" => "r"
There is no reason to make it this complicated, the logs are stored like that because they support multiple storages at the same time, encoding the storage in the id, but this isn't necessary for cache. Just a simple definition of the used cache class should be fine.

2022-04-05 10:24 UTC, matthi4s commented on core/src/Client/MongoDBClient.php
> +            self::$collection = $connection->mclogs->logs;
This should be in a different collection.

2022-04-05 10:24 UTC, matthi4s commented on core/src/Log.php
> +        $storage = $config['caches'][$config['cacheId']]['class'];
A dedicated Cache class that reads the config and uses the correct backend is probably a better way to implement this.

2022-04-05 10:24 UTC, matthi4s commented on core/src/Log.php
> +            $mapURL = (new LauncherMetaMapLocator($version, "server"))->findMappingURL();
This should also be cached as well.

2022-04-05 10:24 UTC, matthi4s commented on core/src/Log.php
> +            $mapURL = (new FabricMavenMapLocator($version))->findMappingURL();
This should also be cached as well.

2022-04-05 10:24 UTC, matthi4s commented on core/src/Log.php
> +    protected function analyse() {
`analyse()` isn't a good name here as that's not all it does, sometimes it even does everything except actually analysing. Just `load()` or something similar is probably a better name.

2022-04-05 11:08 UTC, JulianVennen commented on core/src/Log.php
> +            $mapURL = (new FabricMavenMapLocator($version))->findMappingURL();
Fabric's Yarn mappings usually receive multiple updates.
A temporary cache would probably be good.
How long should that be? 24 hours?

2022-04-05 11:44 UTC, matthi4s commented on core/src/Log.php
> +            $mapURL = (new FabricMavenMapLocator($version))->findMappingURL();
Yes

2022-04-11 15:00 UTC, matthi4s requested changes

2022-04-11 15:00 UTC, matthi4s commented on core/src/Cache/CacheEntry.php
> +    public function getOrGenerateAndSet(callable $generate, ?int $duration = null, ...$args): string
I'm not a fan of this approach, this logic shouldn't be part of the cache entry class and in general, passing callbacks around isn't a good solution.

2022-04-11 15:00 UTC, matthi4s commented on core/src/Log.php
> +        if (get_class($codexLog) === VanillaLog::class) {
The map retrieval (and caching) is a bit long, maybe it would be better in its own function or even its own class.

2022-04-11 15:00 UTC, matthi4s commented on core/src/Client/MongoDBClient.php
> +            self::$collection = $connection->mclogs->{static::COLLECTION_NAME};
You are overwriting the `static::$collection` for all child classes, this probably causes your cache to write into the logs collection. It's probably better to cache the `$connection` in a static field and retrieve the collection through a static function.

2022-04-12 10:20 UTC, matthi4s requested changes

2022-04-12 10:20 UTC, matthi4s commented on core/src/Client/MongoDBClient.php
> +        if (self::$collection === null) {
```suggestion
        if (static::$connection === null) {
```

2022-04-12 10:20 UTC, matthi4s commented on core/src/Client/MongoDBClient.php
> +            $connection = new Client($config['url'] ?? 'mongodb://127.0.0.1/');
```suggestion
            static::$connection = new Client($config['url'] ?? 'mongodb://127.0.0.1/');
```

2022-04-12 10:20 UTC, matthi4s commented on core/src/Client/MongoDBClient.php
> +        return self::$connection->mclogs->{static::COLLECTION_NAME};
It's probably better to call the `Connect()` function here as well instead of calling it separately in the other functions.

2022-04-12 10:20 UTC, matthi4s commented on core/src/Log.php
> +                $urlCache->set($mapURL, 24*60*60);
Do Vanilla URLs change? If not, then we can probably cache them for longer.

2022-04-12 10:20 UTC, matthi4s commented on core/src/Log.php
> +        if ($map !== null) {
You can invert this if statement.

2022-04-21 13:59 UTC, matthi4s requested changes

2022-04-21 13:59 UTC, matthi4s commented on core/src/Log.php
> +            if ($info instanceof VanillaVersionInformation) {
You can use `$this->analysis->getFilteredInsights()` instead.

2022-04-25 12:36 UTC, matthi4s approved these changes

2022-04-25 12:36 UTC, merged